### ISSUE TITLE
pre_commit error breaks copying template

### ISSUE THREAD

**Issue by opunsoars** [pawamoy/copier-poetry#28]
https://github.com/pawamoy/copier-poetry/blob/39fab3f6896f3f1c48ea01dc50cbece37866cf83/project/scripts/post_generation.py.jinja#L33

I keep getting this error when I try to copy this template to empty project folder

```
> Running task 1 of 1: python scripts/post_generation.py
Traceback (most recent call last):
  File "scripts/post_generation.py", line 44, in <module>
    clean_up_precommit()
  File "scripts/post_generation.py", line 33, in clean_up_precommit
    use_precommit = [[ use_precommit ]]
UnboundLocalError: local variable 'use_precommit' referenced before assignment
Traceback (most recent call last):
  File "/Users/opunsoars/.pyenv/versions/immaculate_env/bin/copier", line 8, in <module>
    sys.exit(copier_app_run())
  File "/Users/opunsoars/.pyenv/versions/immaculate_env/lib/python3.8/site-packages/plumbum/cli/application.py", line 638, in run
    inst, retcode = subapp.run(argv, exit=False)
  File "/Users/opunsoars/.pyenv/versions/immaculate_env/lib/python3.8/site-packages/plumbum/cli/application.py", line 633, in run
    retcode = inst.main(*tailargs)
  File "/Users/opunsoars/.pyenv/versions/immaculate_env/lib/python3.8/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/Users/opunsoars/.pyenv/versions/immaculate_env/lib/python3.8/site-packages/copier/cli.py", line 66, in handle_exceptions
    return method(*args, **kwargs)
  File "/Users/opunsoars/.pyenv/versions/immaculate_env/lib/python3.8/site-packages/copier/cli.py", line 244, in main
    worker.run_copy()
  File "/Users/opunsoars/.pyenv/versions/immaculate_env/lib/python3.8/site-packages/copier/main.py", line 205, in __exit__
    raise value
  File "/Users/opunsoars/.pyenv/versions/immaculate_env/lib/python3.8/site-packages/copier/cli.py", line 244, in main
    worker.run_copy()
  File "/Users/opunsoars/.pyenv/versions/immaculate_env/lib/python3.8/site-packages/copier/main.py", line 751, in run_copy
    self._execute_tasks(self.template.tasks)
  File "/Users/opunsoars/.pyenv/versions/immaculate_env/lib/python3.8/site-packages/copier/main.py", line 284, in _execute_tasks
    subprocess.run(task_cmd, shell=use_shell, check=True, env=local.env)
  File "/Users/opunsoars/.pyenv/versions/3.8.6/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'python scripts/post_generation.py' returned non-zero exit status 1.
```

I use py3.8.6

**Comment by pawamoy** [comment]
Hello, thanks for the report. I don't really maintain this template anymore. I can push a quick fix that removes use of pre-commit. Would that be OK to you? Otherwise PRs are welcome :slightly_smiling_face:

**Comment by pawamoy** [comment]
Yeah the template is too old and it's too much work to make it work. As stated in the readme, PRs are welcome, otherwise you can fork and adapt to your needs :slightly_smiling_face:  Closing!
